name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Set current date as env variable
      run: echo "NOW::$(date +'%Y%m.%d%H.%M%S')" >> $GITHUB_ENV
      
    - name: Echo current date
      run: echo $NOW
        
    - name: Build
      run: dotnet build --no-restore --configuration Release -p:Version=$NOW
